## Numpy Quiz1

Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열 생성

In [ ]:
import numpy as np

In [ ]:
# 차원 갯수와 행이나 열을 정했을 때 갯수를 빠르게 결정될 때 사용
ar = np.arange(10)
ar1 = ar.reshape(2, 5)
ar2 = ar.reshape(2, -1)
ar3 = ar.reshape(-1, 2, 5)
print(ar1)
print(ar2)
print(ar3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[0 1 2 3 4]
  [5 6 7 8 9]]]


Q2. reshape(-1,-1)을 이용 1차원을 2차원, 3차원으로 2차원을 1차원 3차원으로 3차원을 1차원 2차원으로 변환

In [ ]:
# reshape(-1,-1)을 이용 1차원을 2차원, 3차원으로 2차원을 1차원 3차원으로 3차원을 1차원, 2차원으로 변환
a = np.arange(10)
print("1차원 → 2차원 : \n", a.reshape(2, -1), '\n')
print("1차원 → 3차원 : \n", a.reshape(-1, 2, 5), '\n')

print("2차원 → 3차원 : \n", a.reshape(-1, 2, 5), '\n')
print("2차원 → 1차원 : \n", a.reshape(-1), '\n')

print("3차원 → 1차원 : \n", a.reshape(-1), '\n')
print("3차원 → 2차원 : \n", a.reshape(2, -1))


1차원 → 2차원 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]] 

1차원 → 3차원 : 
 [[[0 1 2 3 4]
  [5 6 7 8 9]]] 

2차원 → 3차원 : 
 [[[0 1 2 3 4]
  [5 6 7 8 9]]] 

2차원 → 1차원 : 
 [0 1 2 3 4 5 6 7 8 9] 

3차원 → 1차원 : 
 [0 1 2 3 4 5 6 7 8 9] 

3차원 → 2차원 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


Q3. Q1 1차원 배열을 실수형으로 변환

In [ ]:
# Q1 1차원 배열을 실수형으로 변환
print(ar.astype(float))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


Q4. Q1의 dtype을 구하시오.

In [ ]:
# Q1의 dtype
print(ar.dtype)

int64


Q5. 주어진 배열에서 음수 값을 모두 0으로 변경하세요.

arr = np.array([-5, -3, -1, 0, 1, 3, 5])

In [ ]:
arr = np.array([-5, -3, -1, 0, 1, 3, 5])
# np.where(arr < 0, 0, arr)
arr[arr < 0] = 0
print(arr)

[0 0 0 0 1 3 5]


Q6. 1 ~ 100 까지 배열에서 3의 배수인 것만을 출력

In [ ]:
arr = np.arange(1, 101)
print(arr[arr % 3 == 0])

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


Q7. 1 ~ 100 까지 배열에서 5의 배수이면서 2의 배수인 것만을 출력

In [ ]:
arr = np.arange(1, 101)
print(arr[(arr % 5 == 0) & (arr % 2 == 0)])

[ 10  20  30  40  50  60  70  80  90 100]


Q8. 1 ~ 100 까지 배열에서 3의 배수이거나 5의 배수인 것만을 출력

In [ ]:
arr = np.arange(1, 101)
print(arr[(arr % 3 == 0) | (arr % 5 == 0)])

[  3   5   6   9  10  12  15  18  20  21  24  25  27  30  33  35  36  39
  40  42  45  48  50  51  54  55  57  60  63  65  66  69  70  72  75  78
  80  81  84  85  87  90  93  95  96  99 100]


Q9. 101 ~ 150 사이의 정수를 랜덤하게 추출, 2행 5열 다차원 배열을 생성 후 전치하세요

In [ ]:
arr = np.random.randint(101, 151, size=(2, 5))
print(arr, '\n')
print(arr.T)

[[117 101 108 137 140]
 [130 108 124 149 141]] 

[[117 130]
 [101 108]
 [108 124]
 [137 149]
 [140 141]]


Q10. 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하세요.

In [ ]:
arr = np.random.randn(5, 5)
print(arr)

[[-0.25776882 -0.1752998   0.24834887 -1.62123948  0.90655968]
 [ 0.56885432  0.4390536   1.40613955  0.46962564 -0.18253947]
 [-0.46408044  0.03528981  0.74689091  1.25503669  1.21629182]
 [-0.78695975 -2.05290513  1.2664013  -0.29970089 -0.60841795]
 [-1.0139275  -0.3348855  -0.60125102  0.17414966  0.72701716]]


Q11. original_array를 1차원 배열로 변환하여 출력하세요.

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
print(original_array.flatten())
print(original_array.reshape(-1))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


Q12. 주어진 2차원 배열에서 첫 번째 행을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
view = original_array[0, :]
view[0] = 100
print(original_array)
print(view)

[[100   2   3]
 [  4   5   6]]
[100   2   3]


Q13. 주어진 3차원 배열에서 첫 번째 2차원 배열을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [ ]:
original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
view = original_array[0, :, :]
view[0, 0] = 100
print(original_array)

[[[100   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 10  11  12]]]


Q14. 주어진 2차원 배열을 1차원 배열 view로 reshape하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
view = original_array.reshape(-1)
view[2] = 10
print(original_array)

print(view)
# 결과값이 이렇게 나오지 않는 이유 적어놓기
# [  1   2 100]
# [  4   5   6]


[[ 1  2 10]
 [ 4  5  6]]
[ 1  2 10  4  5  6]


Q15. np.ones((10,10))을 아래와 같이 출력하세요.
```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 ```

In [ ]:
arr = np.ones((10,10))
print(arr, '\n')
# arr[1:-1, 1:-1] = 0
arr[1:9, 1:9] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Q16. Q. 1 ~ 100을 아래와 같이 출력하세요.

```
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]
 ```

In [ ]:
arr = np.arange(1, 101).reshape(10, 10)
print(arr, '\n')

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]] 

[20 19 18 17 16 15 14 13 12 11]


In [ ]:
for i in range(10):
    if i % 2 == 1:
        arr[i] = arr[i][::-1]
# arr[1][::-1] : [20 19 18 17 16 15 14 13 12 11]
# arr[3][::-1] : [40 39 38 37 36 35 34 33 32 31]
# ...
print(arr)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


Q17. np.ones((5,5))을 아래와 같이 출력하세요.
```
[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]]
```

In [ ]:
# 5x5 크기의 배열에 0으로 채워진 2칸 두께의 패딩을 적용하여 9x9 크기의 배열을 생성
z = np.ones((5,5))
np.pad(z, pad_width=2, mode = 'constant', constant_values = 0 )

Q18. np.arange(4)을 이용해서 아래와 같이 출력하세요.
```
[[0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0]]
```

In [ ]:
ar_one = np.ones((5, 5))
ar_one[:, :] = 0
print(ar_one, '\n')
arr = np.arange(4) + 1
print(arr, '\n')

for i in range(4):
   ar_one[i+1, i] = arr[i]
print(ar_one)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[1 2 3 4] 

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [27]:
# 다른 풀이
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

Q19. Q. np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile 함수)
```
[[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0]]
```

In [ ]:
# indexing을 사용하는 방법
arr_zero = np.zeros((8,8), dtype = int)
arr_zero[1::2, ::2] = 1
arr_zero[::2, 1::2] = 1
print(arr_zero, '\n')

ar_tile = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(ar_tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]] 

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Q20. np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.


In [26]:
arr = np.arange(336).reshape(6,7,8)
arr_index = np.unravel_index(100, arr.shape)
print(arr_index)

(1, 5, 4)
