In [1]:
import numpy as np

#### Task1_0611. 주어진 대각 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

D = np.diag([1, 2, 3])

In [2]:
def True_inverse():
    D = np.diag([1, 2, 3])
    print(D, '\n')

    D_inv = np.linalg.inv(D)
    print(D_inv, '\n')

    D_dot = np.dot(D, D_inv)
    print(D_dot, '\n')

    return f'역행렬이 맞습니꽈? : {np.allclose(D_dot, np.identity(3))}'

True_inverse()

[[1 0 0]
 [0 2 0]
 [0 0 3]] 

[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



'역행렬이 맞습니꽈? : True'

#### Task2_0611. 임의의 상삼각 행렬을 생성하고, 그 행렬로 부터 하삼각 행렬을 구하여 출력하세요.

In [4]:
A = np.triu(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))
print(A, '\n')

B = np.tril(A)
print(B)

# 결과값이 대각 행렬이 나옴.

[[1 2 3]
 [0 5 6]
 [0 0 9]] 

[[1 0 0]
 [0 5 0]
 [0 0 9]]


#### Task3_0611. 주어진 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

A = np.array([[4, 7], [2, 6]])

In [7]:
def True_inverse():
    A = np.array([[4, 7], [2, 6]])
    A_inverse = np.linalg.inv(A)
    A_dot = np.dot(A, A_inverse)

    if np.allclose(A_dot, np.identity(2)) == True:
        print("'A'의 역행렬 'A_inverse'는 역행렬이 맞습니다.")
    else :
        print("'A'의 역행렬 'A_inverse'는 역행렬이 아닙니다.")

True_inverse()

'A'의 역행렬 'A_inverse'는 역행렬이 맞습니다.


#### Task4_0611. 주어진 데이터 포인트와 모델 파라미터를 사용하여 선형 회귀 모델의 예측값을 계산하세요.

X = np.array([1, 2, 3])

- 1단계 : 주어진 입력 데이터 포인트 X와 모델 파라미터 θ를 정의.
- 2단계 : 행렬 곱을 사용하여 예측값 y를 계산.

In [30]:
X = np.array([1, 2, 3]) # 1 X 3
theta = np.array([ #  3x2 1 x 2
    [1, 2, -3],
    [2, 3, 4],
    [-3, 4, 5]
])
# 3 X 3

# theta 는 가중치 행렬

linear_output = X * theta
print(y) # y의 예측값

[-4 20 20]


#### Task5_0611. 주어진 입력 벡터와 가중치 행렬을 사용하여 신경망의 단일 계층 출력을 계산하세요.

X = np.array([0.5, 1.0, -1.5])

- 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
- 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.

In [38]:
X = np.array([0.5, 1.0, -1.5])
W = np.array([2, 3, 4])

# 선형 회귀 예측값(Linear Transformation)
linear = np.dot(X, W) # + biases
print(f"예측값 : {linear} \n")

# ReLU 활성화 함수
def relu(x):
    return np.maximum(0, x)

# 출력 계산 (Calcurate Output)
output = relu(linear)
print(f"출력 : {output}")

예측값 : -2.0 

출력 : 0.0


#### Task6_0611. 주어진 입력 벡터에 대해 신경망의 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산하세요.

X = np.array([1, -2, 3])

- 1단계: 입력 벡터 X를 정의.
- 2단계: 가중치 행렬 W와 편향 벡터 b를 정의.
- 3단계: 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산
활성화 함수 적용<br>
output_relu = relu(Z)<br>
output_sigmoid = sigmoid(Z)

In [46]:
# 1단계
X = np.array([1, -2, 3])

# 2단계
W = np.array([
    [0.2, 0.3, -0.4],
    [-0.5, 0.6, -0.7],
    [0.8, -0.9, 1.0]
]) # Weights
b = np.array([1, 2, 3]) # bias

# 3단계
def relu(x):
    return np.maximum(0, x)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

Z = np.dot(X, W) + b # Z = linear
print(Z, '\n')

output_relu = relu(Z)
output_sigmoid = sigmoid(Z)

# 입력이 0보다 크면 원본 그대로 출력, 0보다 작으면 0을 출력
print(f"ReLU : {output_relu}")

# 예측값이 0과 1 사이의 값으로 변환
print(f"Sigmoid : {output_sigmoid}")


[ 4.6 -1.6  7. ] 

ReLU : [4.6 0.  7. ]
Sigmoid : [0.9900482  0.16798161 0.99908895]


#### Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여
x와 y를 구하세요.

$\begin{cases}
3x + 4y = 10 \\
2x + y = 5
\end{cases}$

단계:
1. 계수 행렬 A와 결과 벡터 b를 정의.
2. 행렬 A의 역행렬을 구한다.
3. 역행렬을 사용하여 변수 x를 구한다.

In [22]:
A = np.array([[3, 4], [2, 1]])
b = np.array([10, 5])

A_inv = np.linalg.inv(A)
x, y = np.dot(A_inv, b)
print(f" x = {x}")
print(f" y = {round(y)}")

 x = 2.0
 y = 1


#### Task8_0611. 주어진 2D 평면의 점을 특정 변환 행렬을 사용하여 변환한 후, 변환된 좌표를 원래 좌표로 되돌리세요.

원래 점의 좌표 p와 변환 행렬 T 정의<br>
p = np.array([1, 2])<br>
T = np.array([[2, 0], [0, 3]])

단계
1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
2. 변환 행렬 T를 사용하여 새로운 좌표 p를 계산.
3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p에서 원래 좌표 p를 복원.

In [45]:
# 1. 점의 좌표 p와 변환 행렬 T를 정의
p = np.array([1, 2])
T = np.array([[2, 0], [0, 3]])

# 변환 행렬 T를 사용하여 새로운 좌표 p를 계산
new_p = np.dot(T, p)
print(new_p)

# 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p에서 원래 좌표 p를 복원
original_p = np.dot(np.linalg.inv(T), new_p)
print(original_p)

[2 6]
[1. 2.]
